In [1]:
'№1.3.1'
import numpy as np # type: ignore
matrix = np.zeros((8,8))
for i in range(8):
 for j in range(8):
    if (i + j) % 2 == 0:
        matrix[i][j] = 0
    else:
        matrix[i][j] = 1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [2]:
'№1.3.2'
i = 0
while i < 5:
    y = np.arange(0, 5)
    i += 1
    print(y)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [4]:
'№1.3.3'
import numpy as np # type: ignore
array = np.random.random((3,3,3))
print(array)


[[[0.93189714 0.761529   0.79571733]
  [0.35147927 0.54338664 0.08973442]
  [0.60446087 0.66757035 0.50816495]]

 [[0.47153986 0.01015703 0.54159054]
  [0.40664805 0.86850233 0.67570905]
  [0.39104161 0.54861856 0.16640348]]

 [[0.29376114 0.20341544 0.36042935]
  [0.25082906 0.7972653  0.13520353]
  [0.15047016 0.49554433 0.79208215]]]


In [5]:
'№1.3.4'
import numpy as np # type: ignore
def create_matrix(rows, cols):
 matrix = np.zeros((rows, cols))
 matrix[0, :] = 1
 matrix[-1, :] = 1
 matrix[:, 0] = 1
 matrix[:, -1] = 1
 return matrix
rows = int(input())
cols = int(input())
print(create_matrix(rows, cols))

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
'№1.3.5'
import numpy as np # type: ignore
array = np.random.rand(10)
print(array)
sorted_array = np.sort(array)
print(sorted_array)

[0.49823903 0.37538229 0.41309637 0.7431636  0.89542862 0.01863275
 0.14570637 0.90632133 0.97630673 0.4522207 ]
[0.01863275 0.14570637 0.37538229 0.41309637 0.4522207  0.49823903
 0.7431636  0.89542862 0.90632133 0.97630673]


In [7]:
'#1.3.6'
import numpy as np # type: ignore
matrix = np.array([[1,2,3], [2,3,4], [5,6,7]])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 3)
9
2


In [9]:
'№2.3.1'
import pandas as pd # type: ignore
import numpy as np # type: ignore
a = pd.Series([3,2,3])
b = pd.Series([9,5,6])
def euclidean(a, b):
 diff = (a - b)**2
 sum_diff = diff.sum()
 return np.sqrt(sum_diff)
distance = euclidean(a, b)
print(distance)

7.3484692283495345


In [11]:
'№2.3.2'
import pandas as pd # type: ignore
url = 'https://raw.githubusercontent.com/akmand/datasets/main/glass.csv'
dataframe = pd.read_csv(url)

In [12]:
'N2.3.3'
import pandas as pd # type: ignore
url = 'https://raw.githubusercontent.com/akmand/datasets/main/glass.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(5))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[1:4])
print(dataframe[dataframe['2'] == 13.64].head(2))

         1      2     3     4      5     6     7    8    9  10
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0   1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0   1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0   1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0   1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0   1
           1      2    3     4      5    6     7     8    9  10
211  1.52065  14.36  0.0  2.02  73.42  0.0  8.44  1.64  0.0   7
212  1.51651  14.38  0.0  1.94  73.61  0.0  8.48  1.57  0.0   7
213  1.51711  14.23  0.0  2.08  73.36  0.0  8.62  1.67  0.0   7
(214, 10)
                1           2           3           4           5           6  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000   

In [2]:
'№3.3.2'
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(url)

print(data.head())

minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

data['sepal_length_cm'] = minmax_scaler.fit_transform(data[['sepal_length_cm']])
data['sepal_width_cm'] = standard_scaler.fit_transform(data[['sepal_width_cm']])

print(data.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
